# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SpotifyCanvasAPI.proto

require 'google/protobuf'


descriptor_data = "\n\x16SpotifyCanvasAPI.proto\"Q\n\rCanvasRequest\x12$\n\x06tracks\x18\x01 \x03(\x0b\x32\x14.CanvasRequest.Track\x1a\x1a\n\x05Track\x12\x11\n\ttrack_uri\x18\x01 \x01(\t\"\x98\x02\n\x0e\x43\x61nvasResponse\x12(\n\x08\x63\x61nvases\x18\x01 \x03(\x0b\x32\x16.CanvasResponse.Canvas\x1a\xdb\x01\n\x06\x43\x61nvas\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ncanvas_url\x18\x02 \x01(\t\x12\x11\n\ttrack_uri\x18\x05 \x01(\t\x12-\n\x06\x61rtist\x18\x06 \x01(\x0b\x32\x1d.CanvasResponse.Canvas.Artist\x12\x10\n\x08other_id\x18\t \x01(\t\x12\x12\n\ncanvas_uri\x18\x0b \x01(\t\x1aI\n\x06\x41rtist\x12\x12\n\nartist_uri\x18\x01 \x01(\t\x12\x13\n\x0b\x61rtist_name\x18\x02 \x01(\t\x12\x16\n\x0e\x61rtist_img_url\x18\x03 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

CanvasRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CanvasRequest").msgclass
CanvasRequest::Track = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CanvasRequest.Track").msgclass
CanvasResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CanvasResponse").msgclass
CanvasResponse::Canvas = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CanvasResponse.Canvas").msgclass
CanvasResponse::Canvas::Artist = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CanvasResponse.Canvas.Artist").msgclass
